/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_final;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ddaar
 */
public class Nouveau extends javax.swing.JFrame {

    Modele donne;
    Interface_db menu_principal;

    /**
     * Creates new form nouveau
     */
    public Nouveau(Modele modele, Interface_db menu_principal) {
        donne = modele;
        this.menu_principal = menu_principal;
        initComponents();
        try {
            donne.getResult().moveToInsertRow();
        } catch (SQLException ex) {
            Logger.getLogger(Nouveau.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(true);
        setLocationRelativeTo(null);
    }

    private Nouveau() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        code_l = new javax.swing.JLabel();
        code_t = new javax.swing.JTextField();
        designation_l = new javax.swing.JLabel();
        designation_t = new javax.swing.JTextField();
        code_categorie_l = new javax.swing.JLabel();
        code_categorie_t = new javax.swing.JTextField();
        prix_l = new javax.swing.JLabel();
        prix_t = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        JBajouter = new javax.swing.JButton();
        JBannuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        code_l.setText("code");
        jPanel1.add(code_l);
        jPanel1.add(code_t);

        designation_l.setText("designation");
        jPanel1.add(designation_l);
        jPanel1.add(designation_t);

        code_categorie_l.setText("code categorie");
        jPanel1.add(code_categorie_l);
        jPanel1.add(code_categorie_t);

        prix_l.setText("prix");
        jPanel1.add(prix_l);
        jPanel1.add(prix_t);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 50, 1));

        JBajouter.setText("Ajouter");
        JBajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBajouterActionPerformed(evt);
            }
        });
        jPanel2.add(JBajouter);

        JBannuler.setText("Annuler");
        JBannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBannulerActionPerformed(evt);
            }
        });
        jPanel2.add(JBannuler);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBajouterActionPerformed
        try {
            
            donne.getResult().updateString("CODE", code_t.getText());
            donne.getResult().updateString("DESIGNATION", designation_t.getText());
            donne.getResult().updateString("CODE_CATEGORIE", code_categorie_t.getText());
            donne.getResult().updateDouble("PRIX", Double.valueOf(prix_t.getText()));
            donne.getResult().insertRow();

            donne.select_query();
            donne.dernier();
            //menu_principal.actualiserTextbox();
            
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Nouveau.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBajouterActionPerformed

    private void JBannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBannulerActionPerformed
            setVisible(false);        
//        try {
//            donne.getResult().cancelRowUpdates();
//        } catch (SQLException ex) {
//            Logger.getLogger(Nouveau.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_JBannulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nouveau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBajouter;
    private javax.swing.JButton JBannuler;
    private javax.swing.JLabel code_categorie_l;
    private javax.swing.JTextField code_categorie_t;
    private javax.swing.JLabel code_l;
    private javax.swing.JTextField code_t;
    private javax.swing.JLabel designation_l;
    private javax.swing.JTextField designation_t;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel prix_l;
    private javax.swing.JTextField prix_t;
    // End of variables declaration//GEN-END:variables
}
